#!/bin/bash

function readlinkf() {
	local INITIAL_FOLDER=`pwd`

	local TARGET_FILE=$1

	cd `dirname $TARGET_FILE`
	TARGET_FILE=`basename $TARGET_FILE`

	# Iterate down a (possible) chain of symlinks
	while [ -L "$TARGET_FILE" ]; do
		TARGET_FILE=`readlink $TARGET_FILE`
		cd `dirname $TARGET_FILE`
		TARGET_FILE=`basename $TARGET_FILE`
	done

	# Compute the canonicalized name by finding the physical path 
	# for the directory we're in and appending the target file.
	local PHYS_DIR=`pwd -P`
	local RESULT=$PHYS_DIR/$TARGET_FILE

	# Return to inital folder.
	cd $INITIAL_FOLDER

	echo $RESULT
}

allowed="@rpath /usr/lib/ /System/Library/Frameworks/"

for lib in "$@"; do
	libname=$( basename $lib )
	
	echo "$libname:"

	# Split the linked libraries into an array and count
	saveIFS=$IFS
	IFS=$'\n'
	linked=($( otool -L $lib ))
	IFS=$saveIFS
	total=${#linked[*]}

	# Set dylib ID
	id=(${linked[1]})
	if [[ $id != "@rpath/$libname" ]]; then
		cmd="install_name_tool -id \"@rpath/$libname\" $lib"
		echo $cmd
		read -p "Are you sure? " -n 1 -r
		echo
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			eval $cmd
		fi
		#install_name_tool -id "@rpath/$libname" $lib
	else
		echo "ID Correct"
	fi

	# Ignore the first two lines
	for (( i=2; i<=$(( $total - 1 )); i++ )); do
		ll=(${linked[$i]})
		match=0
		for prefix in $allowed; do
			if [[ $ll =~ ^$prefix ]]; then
				match=1
			fi
		done
		if [[ $match == "0" ]]; then
			# Decent any symlinks
			cll=$( readlinkf "$ll" )
			# If linked to a framework
			f=$( echo $cll | sed -nE "s/.*\/(.*.framework\/.*)/\\1/p" )
			if [ $f ]; then
				#echo "Framework"
				echo $f
				cmd="install_name_tool -change \"$ll\" \"@rpath/$f\" $lib"
				echo $cmd
				read -p "Are you sure? " -n 1 -r
				echo
				if [[ $REPLY =~ ^[Yy]$ ]]; then
					eval $cmd
				fi
			else
				#echo "Dylib"
				cmd="install_name_tool -change \"$ll\" \"@rpath/$( basename $cll )\" $lib"
				echo $cmd
				read -p "Are you sure? " -n 1 -r
				echo
				if [[ $REPLY =~ ^[Yy]$ ]]; then
					eval $cmd
				fi
				#install_name_tool -change "$ll" "@rpath/$( basename $cll )" $lib
			fi
		fi
	done

	echo
done

